#!/usr/bin/env node
/**
 * build-data.js
 * Parses osint-tools-comprehensive.md markdown tables into tools-data.js
 * Run: node web/build-data.js
 */

const fs = require('fs');
const path = require('path');

const INPUT_FILE = path.join(__dirname, '..', 'osint-tools-comprehensive.md');
const OUTPUT_FILE = path.join(__dirname, 'tools-data.js');

const markdown = fs.readFileSync(INPUT_FILE, 'utf-8');
const lines = markdown.split('\n');

let currentCategory = '';
let currentSubCategory = '';
const tools = [];
const seen = new Set(); // deduplicate by link

for (let i = 0; i < lines.length; i++) {
  const line = lines[i].trim();

  // Detect ## Category headers
  if (line.startsWith('## ')) {
    currentCategory = line.replace(/^##\s+/, '').trim();
    currentSubCategory = '';
    continue;
  }

  // Detect ### Sub-category headers
  if (line.startsWith('### ')) {
    currentSubCategory = line.replace(/^###\s+/, '').trim();
    continue;
  }

  // Skip table header rows and separator rows
  if (line.startsWith('|') && (line.includes('Tool Name') || line.includes('---'))) {
    continue;
  }

  // Parse table data rows: | Name | Description | Link |
  if (line.startsWith('|') && currentCategory) {
    const cols = line.split('|').map(c => c.trim()).filter(c => c.length > 0);
    if (cols.length >= 3) {
      const name = cols[0];
      const description = cols[1];
      const link = cols[2];

      // Skip rows that look like headers (Location | Time Zone etc.)
      if (!link.startsWith('http') && !link.startsWith('//')) continue;

      // Deduplicate by normalized link
      const normalizedLink = link.replace(/\/+$/, '').toLowerCase();
      if (seen.has(normalizedLink)) continue;
      seen.add(normalizedLink);

      const displayCategory = currentSubCategory
        ? `${currentCategory} > ${currentSubCategory}`
        : currentCategory;

      tools.push({
        name,
        description,
        link,
        category: displayCategory
      });
    }
  }
}

// Extract unique top-level categories (before " > ")
const categories = [...new Set(tools.map(t => t.category.split(' > ')[0]))];

const output = `// Auto-generated by build-data.js — do not edit manually
// Generated: ${new Date().toISOString()}
// Total tools: ${tools.length}
// Categories: ${categories.length}

const TOOLS_DATA = ${JSON.stringify(tools, null, 2)};

const CATEGORIES = ${JSON.stringify(categories, null, 2)};
`;

fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
console.log(`✅ Generated ${OUTPUT_FILE}`);
console.log(`   Tools: ${tools.length}`);
console.log(`   Categories: ${categories.length}`);
console.log(`   Categories: ${categories.join(', ')}`);
